@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTY0NjY0NzV9.s_maeDbhg4XL7_6p_9nu37E0k3DZJ__2vCnfb5qk7Cw

### contacts index
GET http://localhost:3000/index
Authorization: Bearer {{jwt}}

### contacts show
GET http://localhost:3000/show/1

### contacts create
POST http://localhost:3000/contacts
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"first_name": "Gigga",
"last_name": "Jay",
"email": "BRLOC@gmail.com",
"phone_number": "888-923-3333"
}

### contact Update
PATCH http://localhost:3000/contacts/8
Content-Type: application/json

{
"first_name": "Gigga",
"last_name": "Jay",
"email": "BRLOC@gmail.com",
"phone_number": "888-923-3333"
}


### contact Destroy
DELETE http://localhost:3000/contacts/6


### Session create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name3",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"

}

